### ISSUE TITLE
WIP bør ikke publiseres

### ISSUE THREAD

**Issue by yngvar** [blankoslo/about-blank#27]
Tekst som er under arbeid og ikke ferdig bør ikke publiseres. 
Eksempel: Kapitlet "Bærekraft" er merket med work in progress.  Et av underkapitlene, "Økonomi", er bare noen stikkordd.

**Comment by ehamberg** [comment]
Hvorfor ikke? ¯\_(ツ)_/¯

**Comment by yngvar** [comment]
Hvorfor har vi about.blank.no? 
Jeg oppfatter det er en blanding av å både gi oss ansatte informasjon om hvordan vi tenker vi driver sjappa og litt om hva vi står for, samt å skryte til omverdenen om det samme, i en akkurat passe kul form, uten å bli overkul, dermed også formidle et ikke-uttalt budskap om hvem vi er. 

Jeg synes dette ser uproft ut, jeg synes ikke dette bidrar til å dekke noen av punktene ovenfor, men øker forvirring. Ihvertfall i dette konkrete tilfellet, jeg synes det bikker over og ikke er kult, men uryddig og halvgjort og ikke minst halvtenkt. 

Sånn ser websiden ut akkurat nå:  
![image](https://user-images.githubusercontent.com/50703/77143819-8f434800-6a84-11ea-9fec-7837311572aa.png)

**Comment by ekallevik** [comment]
Synes det er fint at man kan være åpne og ærlige om at dette er et viktig tema, samtidig som man ikke er helt i mål på hvordan man skal ta stilling til det. For min del bidrar _hvordan_ man jobber med dette til å kommunisere ut Blanks verdier på en god måte :) 

Enig i at det må jobbes videre med. Har lagt opp en PR for å hvertfall fikse formatteringen.

**Comment by yngvar** [comment]
Ja, du har rett. At enkelte emner er under arbeid (WIP) er helt fint, så lenge det er korrekt språk, formattering og mulig å forstå noe av det som står der. Det var ikke tilfelle nå.

**Comment by yngvar** [comment]
WIP er helt fint, men alle ting som blir lagt ut på about må være forståelig, ikke uleselig, slik tilfelle var for eksemplet her.
